# Yazi configuration
# Official documentation: https://yazi-rs.github.io/docs/configuration/yazi

[mgr]
# Basic manager settings
show_hidden = false
show_symlink = true
scrolloff = 5
ratio = [1, 4, 3]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false
linemode = "size"
# Mouse support - enabled by default
mouse_events = ["click", "scroll"]

[preview]
# Preview settings
tab_size = 2
max_width = 600
max_height = 900
cache_dir = ""
image_filter = "triangle"
image_quality = 75
sixel_fraction = 15
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

[tasks]
micro_workers = 10
macro_workers = 25
bizarre_retry = 5
image_alloc = 536870912  # 512MB
image_bound = [0, 0]
suppress_preload = false
